### ISSUE TITLE
[BUG] Videos in QGIS are not playable (invalid)

### ISSUE THREAD

**Issue by nicdub** [TempAqua/TempAqua_App#10]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In QGIS, I am not able to view a video attached to a feature, I get a message `invalid` right to the internal video player. The video was correctly uploaded to QFieldCloud from my phone and is correctly downloaded in QGIS. The path of the file (relative to the project) is correct and I can view the video if I open it with an external video player (`C:\Users\ndubois\QField\cloud\tempaqua\video\anchor-point_20230317160657098.MP4`).

The video can be played in QField.

### Expected Behavior

The video should be played.

### Steps To Reproduce

Join a video to a feature in QField (Android), push changes to QFieldCloud, download the changes in QGIS then try to view the video directly in QGIS.

### Environment

```markdown
- OS: Win 11 edu
- QGIS: 3.30.0
```

### Anything else?

@regislon : just fyi

**Comment by regislon** [comment]
screen shot+ install qgis + issue sur qgis

**Comment by 3nids** [comment]
no hints on our side for now, can you create an issue upstream https://github.com/qgis/QGIS/issues/new?assignees=&labels=Bug&template=10_bug_report.yml

**Comment by regislon** [comment]
Hi @3nids I did some tests :   
* .mp4 : file produced by qfiled : NOK
* .avi : sample file : OK

--> it seems that QGIS 3.30 is not able to read MP4 file. Sadly, the official documentaion is lacking information about video capabilities. 

@3nids do you know a way to change the video file format in qfiled app ? I don't have this oportunity on my mobile phone (andoid 13) 
[test_video.zip](https://github.com/TempAqua/TempAqua_App/files/11087320/test_video.zip)

To reproduce this, please find attached a simple QGIS project with these two types of video formats.
