### ISSUE TITLE
[Feature] processing time on qfield cloud 

### ISSUE THREAD

**Issue by regislon** [TempAqua/TempAqua_App#11]
### Is your feature request related to a problem? Please describe.

I have a question that I would like to pose in anticipation of researchers' inquiries, which is neither an issue nor a feature request.

Specifically, I've noticed that the processing time on QfieldCloud is slow, even when attempting to update just one feature. I'm curious whether this slowness may be attributed to the concurrency of all jobs, which necessitates an empty queue prior to processing each feature. If that is indeed the case, would it be possible for a Pro user to receive higher priority in the queue?

### Describe the solution you'd like

quicker response time

**Comment by regislon** [comment]
the pro account does not allow to skip the queue

**Comment by 3nids** [comment]
to follow-up, this is not the case at the moment, but planned in the next release (pro will be put on top of the list)
