### ISSUE TITLE
Problèmes/questions courants

### ISSUE THREAD

**Issue by nicdub** [TempAqua/TempAqua_App#4]
Liste des problèmes et questions liés au projet TempAqua dans le GeoPackage [TempAqua.gpkg](https://github.com/TempAqua/TempAqua_App/blob/main/qgis/TempAqua.gpkg)

- [ ] avec l'app mobile, les segments entre les points sont synchronisés qu'après une synchronisation (qui est très longue), est-ce possible d'avoir un changement dynamique sans passer par la synchro?
- [ ] avec l'app mobile, si on crée un point et qu'on `pousse les modifications` (sans synchroniser), on récupère les modifs depuis QGIS, le point n'apparaît pas, si on lance derrière une synchro, le point n'apparaît toujours pas, il faut ajouter un nouveau point et synchroniser pour pouvoir le récupérer dans QGIS
- [ ] comment visualiser les images dans QGIS? actuellement les images et path sont bien synchronisés dans QGIS mais je ne parviens pas à visualiser l'image directement dans QGIS
- [ ] peut-on avoir des comptes QFieldCloud pro pour tester la saisie collaborative?

@regislon FYI

**Comment by regislon** [comment]
split this issue in 4 distincts issues
