### ISSUE TITLE
[BUG] segments automatic drawing is not working in mobile app 

### ISSUE THREAD

**Issue by regislon** [TempAqua/TempAqua_App#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

avec l'app mobile, les segments entre les points sont dessinés qu'après une synchronisation (qui est très longue). 

### Expected Behavior

Les polygones de la couches virtuelles doivent se générer à l'ajout de nouveaux features dans la couche de base. 

### Steps To Reproduce

Add or move a feature in the point layer

liés au projet TempAqua dans le GeoPackage [TempAqua.gpkg](https://github.com/TempAqua/TempAqua_App/blob/main/qgis/TempAqua.gpkg)

### Environment

```markdown
mobile app. Qgis desktop OK
```

**Comment by regislon** [comment]
@nicdub teste d'envoyer le projet  par email sur son natel pour vérifier que ce n'est pas qfieldCloud qui change le comportement de la couche virtuelle.

**Comment by regislon** [comment]
If I transfer this [project](https://github.com/TempAqua/TempAqua_App/files/10811571/could.zip) via email and load it into Qfield mobile app, the virual layer works as expected (segments are created). 

Therefore it seems to be qfieldCloud that changes the behaviuor of the virtual layer. @3nids could you please have a look ? 

The qgis project attached is directly taken from [this project](https://github.com/TempAqua/TempAqua_App/blob/main/qgis/TempAqua.gpkg) - just packaged with the qfield plugin.

**Comment by 3nids** [comment]
go to qFieldSync project configuration and set the virtual layer as "direct access"

![image](https://user-images.githubusercontent.com/127259/225240858-3fec1df3-f6da-447f-a2fc-bb5dc1e79892.png)

**Comment by nicdub** [comment]
Thank you, now the segments are redrawn live, it works as expected.

**Comment by 3nids** [comment]
upstream issue https://github.com/opengisch/qfieldsync/issues/514

**Comment by 3nids** [comment]
@regislon for your info, the upstream issue has been fixed and will be available in next release (max 2 weeks)
