### ISSUE TITLE
[BUG] mobile <-> client sychronisation 

### ISSUE THREAD

**Issue by regislon** [TempAqua/TempAqua_App#8]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. app mobile :  on crée un feature (point) 
2. on pousse les modifications (sans synchroniser)
3. on récupère les modifs depuis QGIS (via le plugin qfield).
 -> le feature n'apparait pas 

4. app mobile : on sychronise 
5. on récupère les modifs depuis QGIS (via le plugin qfield).
 -> le feature n'apparait pas 

6. app mobile :  on crée un nouveau feature (point) 
7. app mobile : on sychronise 
-> les features apparaissent

@nicdub peux-tu confirmer que cela est bien la description du problème ?

### Expected Behavior

les features sont transmis dès le point 3 ci-dessus

### Steps To Reproduce

cd current behaviour

**Comment by nicdub** [comment]
@regislon c'est bien ça

**Comment by regislon** [comment]
effectuer une nouvelle tentative, si cela ne fonctionne pas, envoyer l'ID du job depuis QfieldCloud

**Comment by regislon** [comment]
I've added the test rl feature (with picture) : 

![image](https://user-images.githubusercontent.com/97044425/220852676-b890387c-fdd6-4fcd-8752-fab32311e28b.png)



After pushing the modification from the mobile app, I have two changes : 

![image](https://user-images.githubusercontent.com/97044425/220852819-618405f4-668e-465c-a3ec-656571a2429e.png)

[8c149336 ](https://app.qfield.cloud/a/regislon/TempAqua__QFieldCloud_/changes?id=8c149336-288e-45f9-b775-659b74286b0f&change-preview=1 )is the picture 

[3e0acbee ](https://app.qfield.cloud/a/regislon/TempAqua__QFieldCloud_/changes?id=3e0acbee-b354-47e4-a86c-1d449d323d14&change-preview=1 )is the picture, but without geometry in the map (but included in the Json)

![image](https://user-images.githubusercontent.com/97044425/220853212-f5bc5209-25ad-4f44-ba1f-01d3cf79a967.png)

`{
  "new": {
    "geometry": "Point (6.71421762163155922 46.58779408600538829)",
    "attributes": {
      "fid": null,
      "uuid": "{38fe9ffd-e7de-4605-b235-1425f5b08c5a}",
      "fid_1": 119,
      "point_id": "test rl",
      "description": null,
      "location_type": null,
      "catchment_name": null,
      "parent_point_id": "BA98"
    }
  },
  "uuid": "3e0acbee-b354-47e4-a86c-1d449d323d14",
  "method": "create",
  "localPk": "119",
  "clientId": "bba81edb-0fbf-4e00-a42a-267e44d4661a",
  "exportId": "0a1591f0-447f-4d37-894c-fcb485019aeb",
  "sourcePk": "",
  "localLayerId": "anchor_point_bb75bc6d_7147_41fe_9309_45d772ebf2a0",
  "localLayerCrs": "EPSG:4326",
  "sourceLayerId": "anchor_point_bb75bc6d_7147_41fe_9309_45d772ebf2a0",
  "localLayerName": "anchor_point"
}`


Jobs interface : 

![image](https://user-images.githubusercontent.com/97044425/220853429-44ca2835-cba3-43ff-a2d5-6c88de76f3ea.png)

job ddfac586-a5e3-45aa-982e-30d67c7a4c1b : 

![image](https://user-images.githubusercontent.com/97044425/220853527-ee374bb9-dd2a-4b30-ab4a-66988d8fc41e.png)

job ff3f146f-d4d5-43d0-b8f4-290a913d5698 : 

![image](https://user-images.githubusercontent.com/97044425/220853634-7681660d-c95b-413a-9076-6220f5fe3438.png)


-> I've **not**  reproduced @nicdub issue. ? If needed, here is the [could project](https://github.com/TempAqua/TempAqua_App/files/10811519/could.zip)

![image](https://user-images.githubusercontent.com/97044425/220858535-3d20564c-afcb-4819-99f2-5497f6e8a44e.png)


![image](https://user-images.githubusercontent.com/97044425/220858588-6a4bbdc5-963b-4c69-9b3b-f4770006ae87.png)

![image](https://user-images.githubusercontent.com/97044425/220858610-44bd8b34-5e83-4118-a8c5-baf542bbb0c7.png)
 

@nicdub could you please retry ?

**Comment by regislon** [comment]
solved
